# Generated by Django 5.1.7 on 2025-03-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coursesWithGrades',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
